### ISSUE TITLE
Feat: adding newsletter to subscribe

### ISSUE THREAD

**Issue by SuyashM10** [SuyashM10/Prime-News#11]
Implement a newsletter subscription feature to keep users updated with the latest news, updates, and features

**Comment by geeta052** [comment]
Assign me this issue .
![Screenshot 2024-08-29 133402](https://github.com/user-attachments/assets/93e3bccb-721a-46b7-a936-6ef92d0ad739)
![Screenshot 2024-08-29 133600](https://github.com/user-attachments/assets/dbbe61e8-93af-46d8-b443-28df5f9f6742)

**Comment by SuyashM10** [comment]
Yes, I've assigned the issue to you.
