### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by SuyashM10** [SuyashM10/Prime-News#5]
While searching for news , they are not filtered on basis of category or tags. Its not implemented in code.

**Comment by geeta052** [comment]
@SuyashM10 Assign me this issue under GSSOC24 for contributing to this project

**Comment by geeta052** [comment]
@SuyashM10 Please check out this newly added search bar with working functionality
![Screenshot 2024-08-25 200744](https://github.com/user-attachments/assets/2df8aa69-9dbd-4a78-9674-6fd92db57220)
![Screenshot 2024-08-25 201724](https://github.com/user-attachments/assets/b28e9a60-c8a4-4f22-bae9-ca1e6b4d275a)
